# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - windowsgithub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_e0b5a7e4f2c24ab4b9e5a84a4f21b69b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_330d2a5b96ef44aaa87e189936fd0f03 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_e0b5a7e4f2c24ab4b9e5a84a4f21b69b }}/azure-app-service/windows/parkingpage:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'windowsgithub'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a84796652a1b4cf9aff53ae6b27b5882 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_e0b5a7e4f2c24ab4b9e5a84a4f21b69b }}/azure-app-service/windows/parkingpage:${{ github.sha }}'